<a href="https://colab.research.google.com/github/ManasAkhare/NPTEL_2026-27_OddSem_R/blob/main/23102C0017_R_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = matrix(nrow = 4, ncol = 3, data = c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [2]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [3]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [4]:
x = matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [6]:
d = diag(1, nrow=3, ncol=3)
d
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [7]:
x = matrix(nrow = 4, ncol = 2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [10]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x
rowSums(x)
colSums(x)
rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

[1] 3 4 5 6

[1] 2.5 6.5

In [13]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)
x
x[3, ]
x[,2]
x[4:5, 2:3]
x[c(1,4), c(1,3)]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [15]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
x+5
x-5
5*x
x/2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [20]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
x
y
x+y
x-y
4*x
x+4*x
4*x-x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [21]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x%*%y
y%*%x

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [23]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
t(x)
t(x) %*% x
x%*%t(x)
crossprod(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [24]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
rbind(x, y)
cbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [26]:
y = matrix(nrow=2, ncol=2, byrow=T, data=c(84, 100, 100, 120))
solve(y)
eigen(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [32]:
x=8
(x<10)||(x<2)
x = 18
(x<10)||(x<2)
x = c(8,18)
(x<10)|(x<2)

[1] TRUE

[1] FALSE

[1]  TRUE FALSE

In [38]:
x=5
(x<10)&&(x>2)
x=15
(x<10)&&(x>2)
x=c(8, 18)
(x<10)&(x>2)
x=1:6
(x>2) & (x<5)
x[(x>2) & (x<5)]
(x>2)|(x<5)
x[(x>2)|(x<5)]

[1] TRUE

[1] FALSE

[1]  TRUE FALSE

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

In [41]:
x = TRUE
y = FALSE
x&y
x|y
!x

[1] FALSE

[1] TRUE

[1] FALSE

In [47]:
x = 5
logical1 = (x>2)
logical1
is.logical(logical1)
logical2 = (x<10)
logical2
is.logical(logical2)
logical3 = (x!=5)
logical3
is.logical(logical3)
logical4 = (2*x > 11)
logical4
is.logical(logical4)
logical5 = (3*x < 20)
logical5
is.logical(logical5)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

In [48]:
8>7
7>5
7>7
7>=7
8<8
8<=8
8!=9
9!=9
7==7
7==8
x = TRUE
!x

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

In [49]:
x = c(1, 2, 3)
y = c(4, 5, 6)
x>y
x<y
x!=y
x==y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [50]:
isTRUE(8<6)
isTRUE(8>6)
isFALSE(5<8)
isFALSE(5>8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE