In [1]:
2^0.5
2**0.5
2^-0.5

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [3]:
c(2, 3, 5, 7) ^ 3
c(2, 3, 5, 7) ^ c(2, 2.5)

[1]   8  27 125 343

[1]   4.00000  15.58846  25.00000 129.64181

In [4]:
c(2, 3, 5, 7) ^ c(2, 3, 4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [8]:
2 %/% 2
5 %/% 2
9 %/% 5
c(5, 7, 9, 11) %/% c(2, 3)

[1] 1

[1] 2

[1] 1

[1] 2 2 4 3

In [7]:
c(3, 5, 7) %/% c(2, 3)

Warning message in c(3, 5, 7)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 3

In [11]:
2%%2
3%%2
7%%4
c(2, 3, 5, 7) %% 3
c(3, 4, 7, 8) %% c(2, 3)

[1] 0

[1] 1

[1] 3

[1] 2 0 2 1

[1] 1 1 1 2

In [12]:
c(5, 7, 9) %% c(2, 3)

Warning message in c(5, 7, 9)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 1

In [16]:
max(2, 3.5, -7)
max(c(2, -3.5, -7))

min(4, -5, -3)
min(c(3, -7, 9))

mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 3.5

[1] 2

[1] -5

[1] -7

[1] 2

[1] 3

In [20]:
abs(-4)
abs(c(-2, -3, -5, -7))

sqrt(4)
sqrt(c(4, 9, 16, 25))

sum(c(4, 7, 11, 25))
prod(c(2, 3, 5, 7))

round(1.23)
round(1.83)

log(10)
log(exp(1))
log(c(10, 20, 30))

[1] 4

[1] 2 3 5 7

[1] 2

[1] 2 3 4 5

[1] 47

[1] 210

[1] 1

[1] 2

[1] 2.302585

[1] 1

[1] 2.302585 2.995732 3.401197

In [22]:
x1 = c(2, 3, 4, 5)
x1
x2 = x1^2
x2

[1] 2 3 4 5

[1]  4  9 16 25

In [23]:
c(2, 3, 4, 5) + sum(2, 4, 6, 8) *prod(c(2, 3))
abs(c(-4, 7, -9, 10)) - sum(c(1, 2, 3, 4)) * prod(c(2, 3))

[1] 122 123 124 125

[1] -56 -53 -51 -50

In [30]:
x = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8))
x
x[3, 2]
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 7

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

In [28]:
y = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8