<a href="https://colab.research.google.com/github/ManasAkhare/NPTEL_2026-27_OddSem_R/blob/main/R_09_23102C0017.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [4]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [5]:
d = date()
cat("Today's date is:", d, "\n")

Today's date is: Thu Sep 24 04:47:57 2026

In [6]:
x = 1:10
x
cat(x, sep = " ++ ")
cat("\n")
cat(x, sep=" / ")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [7]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [8]:
cat("The square root of", x, "is approximately", format(sqrt(x), digits=3,), "\n")

The square root of 7 is approximately 2.65

In [9]:
evenno = c(2, 4, 6, 7, 10)
evenno
cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  7 10

The first few even numbers are: 2 4 6 7 10 ...

In [11]:
x = 1:10
x
cat(x, fill=2, labels = paste("(", letters[1:10], "):"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [12]:
paste(1:12)
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [13]:
paste("Everybody", "loves", "R Programming.")
paste("Everybody", "loves", "R Programming.", sep="*")
paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

In [14]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [15]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

In [16]:
paste(1, " is the first" 2, " is second", 3, " is third", sep = "#")
paste(1, " is the first    " 2, " is second        ", 3, " is third        ", sep = "#")

ERROR: Error in parse(text = input): <text>:1:26: unexpected numeric constant
1: paste(1, " is the first" 2
                             ^

In [17]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [18]:
x = paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [19]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [20]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [21]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split="!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [22]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split="&!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [23]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
y = strsplit(x, split="!&")
y
y[[1]][1]
y[[1]][2]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

In [25]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
dates
datesplt = strsplit(dates, "-")
datesplt
datemat = matrix(unlist(datesplt), nrow=4, ncol=3, byrow=TRUE)
datemat
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)
datematrix

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [27]:
strsplit("Shalabh", split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [28]:
x = "R course 24.07.2022"
x
y = "Number of participants: 25"
y
nchar(x)
nchar(y)
nzchar(x)
nzchar(y)

[1] "R course 24.07.2022"

[1] "Number of participants: 25"

[1] 19

[1] 26

[1] TRUE

[1] TRUE